# Generated by Django 5.2.2 on 2025-06-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_tutorial_video_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='theme',
            field=models.CharField(choices=[('blue', 'Blue Theme'), ('red', 'Red Theme'), ('green', 'Green Theme'), ('purple', 'Purple Theme')], default='blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
