# Generated by Django 5.2.2 on 2025-06-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_theme_alter_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='ad_banners',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='referral',
            name='working_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('clicked', 'Clicked'), ('converted', 'Converted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
