# Generated by Django 5.2.2 on 2025-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer_ad_banners_offer_logo_referral_working_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='tutorial_video',
        ),
        migrations.AddField(
            model_name='offer',
            name='tutorial_videos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
