# Generated by Django 5.2.2 on 2025-06-10 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_remove_offer_ad_banners_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='referral',
            name='visitor_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'offer'), name='unique_user_offer'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('visitor_identifier', 'offer'), name='unique_visitor_offer'),
        ),
    ]
