# Generated by Django 5.2.2 on 2025-06-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_alter_offer_id_alter_referral_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
