# Generated by Django 5.2.2 on 2025-06-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_tutorialvideo_remove_referral_unique_user_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='google_form_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='requires_contact_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='requires_google_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutorialvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutorialvideo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
