# Generated by Django 5.2.2 on 2025-06-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_advertiser_offer_advertiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
