# Generated by Django 5.2.2 on 2025-06-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_apiusage_pendingverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
