# Generated by Django 5.2.2 on 2025-06-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
