# Generated by Django 5.2.2 on 2025-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_googleformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='visitor_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
