# Generated by Django 5.2.2 on 2025-06-12 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_contactinfo_visitor_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='offers.referral')),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'session_key'], name='offers_refe_ip_addr_eb6b13_idx')],
                'unique_together': {('referral', 'ip_address', 'session_key')},
            },
        ),
    ]
