# Generated by Django 5.2.2 on 2025-06-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_referralclick'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='referralclick',
            name='offers_refe_ip_addr_eb6b13_idx',
        ),
        migrations.AlterUniqueTogether(
            name='referralclick',
            unique_together={('referral', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='referralclick',
            index=models.Index(fields=['ip_address'], name='offers_refe_ip_addr_8b9e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='referralclick',
            index=models.Index(fields=['clicked_at'], name='offers_refe_clicked_e53e4a_idx'),
        ),
    ]
