# Generated by Django 5.2.2 on 2025-06-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0021_remove_referralclick_offers_refe_ip_addr_eb6b13_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
