# Generated by Django 5.2.2 on 2025-06-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0022_apilog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileValidationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('is_valid', models.BooleanField()),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
