# Generated by Django 5.2.2 on 2025-06-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0023_mobilevalidationcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
