# Generated by Django 5.2.2 on 2025-06-13 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0024_offer_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('ecommerce', 'Ecommerce'), ('finance', 'Finance'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='conversion_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('sale', 'Sale'), ('signup', 'Signup')], default='lead', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='requires_conversion_proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='requires_lead_form',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConversionProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='conversion_proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
